# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: **************

google:
  client_id: **************.apps.googleusercontent.com
  client_secret: **************

cockroachdb:
  database: **************
  user: **************
  password: **************
  host: **************.cockroachlabs.cloud
  port: *****
  cluster: **************
